### ISSUE TITLE
FATAL: Unable to import ibmi_fix_repo due to invalid syntax

### ISSUE THREAD

**Issue by robinsg** [IBM/ansible-for-i#128]
Collection v1.6

When trying to use ibmi_fix_repo in a playbook it returns the above error:

Sample code:

```
---
- hosts: "{{ repo_server }}"
  gather_facts: false
  collections:
   - ibm.power_ibmi
  environment:
        https_proxy: http://my.proxy_server.name:11000

  tasks:
    - name: retrieve fix orders in downloading status
      ibmi_fix_repo:
        action: "find"
        type: 'download_status'
        checksum: false
        parameters:
          - {'download_status': 'DOWNLOADING'}
      register: result
```

```
TASK [retrieve fix orders in downloading status] ***************************************************************************
fatal: [my_ibmi]: FAILED! => {"msg": "Unable to import ibmi_fix_repo due to invalid syntax"}
```

I also note that running ansible-doc fails too:

```
[grobinso@my_server IBMiPTFs (main)]$ ansible-doc ibm.power_ibmi.ibmi_fix_repo
ERROR! module ibm.power_ibmi.ibmi_fix_repo missing documentation (or could not parse documentation): invalid syntax (<unknown>, line 365)
```

I can successfully use other modules and view their documentation.
