### ISSUE TITLE
Ansible Automation Platform 2.x execution environments

### ISSUE THREAD

**Issue by aklyachkin** [IBM/ansible-for-i#133]
Ansible Automation Platform 2.x provides the new way of execution of playbooks by using execution environments (https://docs.ansible.com/automation-controller/latest/html/userguide/execution_environments.html). An execution environment is a container image with all required collections.

Unfortunately it doesn't work with ibm.power_ibmi collection. 

execution-environment.yml:
```
---
version: 1
dependencies:
  galaxy: requirements.yml
```

requirements.yml:
```
---
collections:
  - name: ibm.power_ibmi
```

Building of the execution environment:

```
$ ansible-builder build
...showing last 20 lines of output...
+ '[' -f bindep.txt ']'
+ bindep -l newline
+ sort
+ '[' centos == centos ']'
+ bindep -l newline -b epel
+ sort
+ grep -Fxvf /output/bindep/run.txt /output/bindep/stage.txt
+ true
+ rm -rf /output/bindep/stage.txt
++ bindep -b compile
++ true
+ compile_packages=python
+ '[' '!' -z python ']'
+ /usr/bin/dnf install -y python
CentOS Stream 8 - Extras common packages        9.0 kB/s | 3.1 kB     00:00
No match for argument: python
There are following alternatives for "python": python2, python36, python38, python39
Error: Unable to find a match: python
[3/3] STEP 1/5: FROM quay.io/ansible/ansible-runner:latest
Error: error building at STEP "RUN assemble": error while running runtime: exit status 1

An error occured (rc=125), see output line(s) above for details.
```

All other IBM Power collections (ibm.power_*) work without any problems. The problem exist only with ibm.power_ibmi collection. I didn't find anything in the source code, but the python dependency is somewhere declared wrong.

**Comment by changlexc** [comment]
I think the key maybe bindep in power_ibmi. power_ibmi only support python3.6 and above. What's the python version on your system, I think you may need to use python3(or python3.x) 's pip3 to install the ansible-builder to let the ansible-builder run as python3.

**Comment by changlexc** [comment]
I run complete without issue, this is my files,
execution-environment.yml:
```
---
version: 1
dependencies:
  galaxy: requirements.yml
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
```

requirements.yml
```
---
version: 1
dependencies:
  galaxy: requirements.yml
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
```

bindep.txt
```
-# This is a cross-platform list tracking distribution packages needed by this collection;
# see https://docs.openstack.org/infra/bindep/ for additional information.

python >=3.6,<=3.8
```
You may need to first clean up the old one in your output context directory, for example, for me, is /Users/changle/context

**Comment by changlexc** [comment]
I run complete without issue, this is my 
execution-environment.yml:
```
---
version: 1
dependencies:
  galaxy: requirements.yml
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
```

and my requirements.yml
```
---
version: 1
dependencies:
  galaxy: requirements.yml
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
```

You may need to first clean up the old one in your output context directory, for example, for me, is /Users/changle/context
