### ISSUE TITLE
is it possible to get all rows from ibmi_fix_repo with action find?

### ISSUE THREAD

**Issue by syahrul-aiman** [IBM/ansible-for-i#161]
As per subject.

The following returns empty list:

```yaml
- ibmi_fix_repo:
    action: 'find'
    type: 'ptf_group'
    parameters: []
```

**Comment by syahrul-aiman** [comment]
this workaround works:

```yaml
- ibmi_fix_repo:
    action: 'find'
    type: 'ptf_group'
    parameters:
      - additional_param: "ORDER BY id"
```
