### ISSUE TITLE
ibmi_fix_imgclg multiple IPLs

### ISSUE THREAD

**Issue by ceetonice** [IBM/ansible-for-i#183]
When installing PTFs with module ibmi_fix_imgclg. If a TR is apart of the install and requires and IPL for prerequisites. The process goes: run ansible script, installs ptf, requires IPL for prerequisites, run ansible script, then IPL again. If I do a normal install it only requires one IPL. Is there a way to correct this?

non-ansible way:
CRTIMGCLG PTF2017MAY DIR('/IMGCAT/2017MAYPTF') CRTDIR(*NO)
ADDIMGCLGE PTF2017MAY FROMFILE('/imgcat/2017MAYPTF/C7068720_1.bin') TOFILE(C7068720_1.bin)
Load Device
INSPTF LICPGM((*ALL)) DEV(OPTVRT01) INSTYP(*DLYALL) PMTMED(*MLTSRV)

With Ansible:
- name: Connect to IBMi
  hosts: "{{ ibmi }}"

  collections:
    - ibm.power_ibmi

  tasks:

    - name: Install a list of PTFs from image catalog
      ibm.power_ibmi.ibmi_fix_imgclg:
        product_id:
          - '*ALL'
        src: "{{ fix_install_path }}"
        apply_type: "{{ apply_type }}"
        rollback: True
      register: ptf_results

    - name: Print PTF Install Start
      debug:
        msg: 'install start: {{ ptf_results.start }}'

    - name: Print PTF Install End
      debug:
        msg: 'install end: {{ ptf_results.end }}'

**Comment by syahrul-aiman** [comment]
If I'm not mistaken, you can make use of the `ibmi_reboot` module, example:

```yaml
tasks:

- name: Reboot / IPL the machine before PTF Install
  ibm.power_ibmi.ibmi_reboot:

- name: Print PTF Install Start
  debug:
    msg: 'install start: {{ ptf_results.start }}'

- name: Install a list of PTFs from image catalog
  ibm.power_ibmi.ibmi_fix_imgclg:
    product_id:
    - '*ALL'
    src: "{{ fix_install_path }}"
    apply_type: "{{ apply_type }}"
    rollback: True
    register: ptf_results

- name: Print PTF Install End
  debug:
    msg: 'install end: {{ ptf_results.end }}'
```
