### ISSUE TITLE
Integration PowerVC and Ansible controller on IBM i

### ISSUE THREAD

**Issue by mad5bo** [IBM/ansible-for-i#78]
Hi, 

I would like to have the considerations to integrate PowerVC and Ansible Controller for deployment VMs. For example, to get started Ansible controller and PowerVC (Standard or Manager) we should import a public key generated from the Ansible controller to IBM PowerVC ), shouldn´t we?
![image](https://user-images.githubusercontent.com/68882369/108905285-4a158780-75fe-11eb-80ef-7f9494254ebd.png)

Afterwards, edit the hosts file, adding  the following lines
![image](https://user-images.githubusercontent.com/68882369/108906378-96ad9280-75ff-11eb-8e9b-2feb98ba3136.png)

Finally, run the role
https://github.com/IBM/ansible-for-i/tree/devel/roles/deploy_vm_via_powervc

Any other consideration, tip or hit for this procedure?

Regards
MAD

**Comment by LiJunBJZhu** [comment]
Hi, 

It is a good point. You can create a key pair on PowerVC, and inject the key to deployed VM via user data.

**Comment by mad5bo** [comment]
Hi @LiJunBJZhu 

It is clear to generate a public key on Ansible controller on IBM i, 
```
# cat /home/qsecofr/.ssh/id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBV4ZyTku2GYNDK7M6bOMDojSKW3xMROvdou5zTjVMnqYDgExyxaHwYXLpZ3lCMeZqQki0HX6ngksydu4D3SUO8bfDDfvMJrKcoX+cRLYkevJ/bPH3CCtUdQkJg8AHuY2Aif8mlizPcnddtv+IQ/5yLZWJNUwYJ9Q/uC4NYbKO5u6DJhYpVrjCHIZhx5edKy71lhXdfkXOy23BX9gjhcyqJYX1NI4Q2dzkKw5Q4fifh6QcvIdjwj7Y2djsdLrODFnAGjWvibtjGPVEgzK5s0UP9PykSaEHHBzaRLzLkeMTw0lRgUGCOeFvWW01vOEYuC3goHun5umDmDEEQ4wGKkoa+RmT/dn/ozsLh4T/mI49gX40zIxKpoc8iNY4X7WEHU7yHgLYSphFnQFmEeTBmM2YEI6qZo6vrV8ndmvrnDgEeTaHAabhitRZqDXYcj62L+4L6D79cDvgL7qKxy8rHY2y/3/PJ/jyg5UFAYYQu1p489Ijrfqc7VR0n/RbfH4g2CM
```
Then on PowerVC copy that public key on Key pair
![image](https://user-images.githubusercontent.com/68882369/112561466-0c9a4a80-8db4-11eb-9062-96edc7f01014.png)

Do you mean to inject the key to deployed VM as simple as selecting the key pair while deploying a new VM?

![image](https://user-images.githubusercontent.com/68882369/112561679-70247800-8db4-11eb-90d0-b871c2e5bb49.png)

or where or how do you inject the key deployed VM via user data?

Thanks in advance!

**Comment by LiJunBJZhu** [comment]
An example of injecting key via userdata. It is to inject key to default user of cloud-init, for example, it is QCIUSER. And it also creates a new user profile named test1 and injects the key to test1 as well.

```
    userdata: |
          #cloud-config
          ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMsx23avIaCwUIYABC
          users:
            - name: test1
              gecos: "Changed by cloud-init"
              expiredate: 2032-09-01
              inactive: False
              lock_passwd: False 
              passwd: 123456677
              ssh_authorized_keys:
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMsx23avIaCwUIYHE+5mFSABC         
  
```
