### ISSUE TITLE
Module ibmi_sql_exeute returns AnsibleUnsafeText type when DELETE from ends in error

### ISSUE THREAD

**Issue by robinsg** [IBM/ansible-for-i#83]
I'm running the following in my playbook:
```
  - name: SQL DELETE where credit limit is less than 9999.00
    ibmi_sql_execute:
      sql: "DELETE FROM {{ library_name }}.{{ srcfile }}
      WHERE CDTLMT < 9999.00"
    register: sql_delete
    ignore_errors: true
    no_log: true
```

If the DELETE FROM finds no rows to delete it causes an error.

The sql_delete.stderr variable contains:

`"stderr": "{'error': '*** error DELETE FROM ANSIBLIB.QCUSTCDT WHERE CDTLMT < 9999.00', 'version': 'XML Toolkit 1.9.2', 'xmlhint': '02000:100:Row not found for DELETE.', 'xmlhint1': '02000:100:Row not found for DELETE.', 'jobipc': '*na', 'jobipcskey': 'FFFFFFFF', 'jobname': 'QSQSRVR', 'jobuser': 'QUSER', 'jobnbr': '007433', 'curuser': 'GROBINSO', 'ccsid': '1146', 'dftccsid': '1146', 'paseccsid': '0', 'syslibl': 'QSYS QSYS2 QHLPSYS QUSRSYS', 'usrlibl': 'QGPL QTEMP'}"`

I want to check sql_delete.stderr.xmlhint as that has the "Row not found for delete" message so I can choose to ignore the error and continue.

When I attempt to get the value of sql_delete.stderr.xmlhint I'm unable to access the value.

If I use:

```
- debug:
       mag: "{{ sql_delete.stderr | type_debug}}"
```

```
It returns:
ok: [ibmi01] => {
    "msg": "AnsibleUnsafeText"
}
```

Why is the module returning Unsafe Text and how do I access the unsafe text data?
